# Generated by Django 5.1.3 on 2024-12-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
